version: '3.8'
services:
  db:
    container_name: phenix-postgres
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-store:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db-store:
